# Generated by Django 3.0.7 on 2020-08-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200730_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_day_end',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_day_start',
            field=models.CharField(default='08:00', max_length=5),
        ),
    ]
