# Generated by Django 3.0.7 on 2020-08-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
        ('mainapp', '0003_auto_20200801_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='places',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='timetable_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.TeacherTimetableBooking'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeacherTimetableBooking',
        ),
    ]
