# Generated by Django 3.0.7 on 2020-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200806_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='1928369128391283', max_length=20),
            preserve_default=False,
        ),
    ]
