# Generated by Django 3.1.2 on 2020-10-19 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profile_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 14, 53, 8, 358951)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_day_end',
            field=models.CharField(default='20:00', max_length=5, verbose_name='Work day end'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_day_start',
            field=models.CharField(default='08:00', max_length=5, verbose_name='Work day start'),
        ),
    ]
