# Generated by Django 3.1.2 on 2020-10-19 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201019_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teacher_registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 16, 40, 59, 452646)),
        ),
    ]
