# Generated by Django 3.0.7 on 2020-08-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_auto_20200801_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTimetableBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.LessonBooking')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TeacherTimetable')),
            ],
        ),
    ]
