# Generated by Django 3.0.7 on 2020-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_teachertimetablebooking_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertimetablebooking',
            name='pending',
        ),
        migrations.AddField(
            model_name='teachertimetablebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('booked', 'booked')], default='pending', max_length=9),
        ),
    ]
