# Generated by Django 3.0.7 on 2020-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200715_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, max_length=30, null=True),
        ),
    ]
