# Generated by Django 3.0.7 on 2020-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200715_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='setting.MEDIA_ROOT/avatar/default.png', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
