# Generated by Django 3.0.7 on 2020-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200715_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatar/default.png', upload_to='avatars'),
        ),
    ]
