# Generated by Django 3.0.7 on 2020-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200715_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars'),
        ),
    ]
